import {chromium} from '@playwright/test';
import {readFile,writeFile,mkdir,copyFile} from 'node:fs/promises';
const config=JSON.parse(await readFile(new URL('./config.json',import.meta.url),'utf8'));
const take=process.argv[2]??'1';
const api=async(path,body)=>{const r=await fetch(config.baseUrl+'/api/'+path,body===undefined?undefined:{method:'POST',headers:{'Content-Type':'application/json','X-Mercury-Client':'1'},body:JSON.stringify(body)});const value=await r.json();if(!r.ok)throw new Error(value.error);return value;};
async function finished(id){for(let i=0;i<180;i++){const r=await api('run/'+id);if(r.status!=='RUNNING')return r;await new Promise(r=>setTimeout(r,500));}throw new Error('Execution exceeded recording budget.');}
await mkdir('demo/raw',{recursive:true});await mkdir('demo/evidence',{recursive:true});
const reset=await api('plan',{request:`Move launch to ${config.resetDate}`,mode:'live',fault:'none'});
if(reset.plan.blockers.length)throw new Error(JSON.stringify(reset.plan.blockers));
await api('execute',{planId:reset.plan.id});const resetReceipt=await finished(reset.plan.id);
if(resetReceipt.verdict!=='SUCCESS')throw new Error('Sandbox reset did not verify.');
console.log(JSON.stringify({take,phase:'reset verified'}));
const browser=await chromium.launch({channel:'msedge',headless:true});
const context=await browser.newContext({viewport:config.viewport,recordVideo:{dir:'demo/raw',size:config.viewport},reducedMotion:'reduce'});
const captureStarted=Date.now();const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(config.baseUrl);await page.getByLabel('Execution mode').selectOption('live');
// Presentation-only crop: no data or results are changed. Account chrome is never recorded.
await page.addStyleTag({content:'.rail,.workspace-mark,.history,.page-footer{display:none!important}main{margin-left:0!important;width:100%!important}.content{max-width:1440px!important;padding:26px 40px!important}.topbar{padding-inline:70px!important}.heading h1{font-size:34px!important}.heading p{font-size:14px!important}.scope-note{font-size:11px!important}.proof-step-label,.eyebrow{font-size:11px!important}td{font-size:14px!important}td small{font-size:11px!important}.proof-steps strong{font-size:28px!important}'});
await page.getByLabel('Controlled fault').selectOption('stale');
await page.mouse.move(1450,850);
const start=Date.now();const elapsed=()=> (Date.now()-start)/1000;
const at=async(seconds)=>{const wait=seconds*1000-(Date.now()-start);if(wait>0)await new Promise(r=>setTimeout(r,wait));};
const marks={take,leadIn:(start-captureStarted)/1000};
await at(8);
const planning=page.waitForResponse(r=>r.url().endsWith('/api/plan'));
await page.getByRole('button',{name:'Analyze impact'}).click();const pResponse=await planning;const preview=await pResponse.json();
if(!pResponse.ok()||preview.plan.blockers.length)throw new Error('Live preview blocked');
marks.discoverySeconds=elapsed()-8;
await page.locator('.workspace-grid').evaluate(el=>el.scrollIntoView({block:'start'}));
await page.mouse.move(1480,850);await page.screenshot({path:`demo/evidence/take-${take}-impact.png`});
await at(37);const executeStart=Date.now();await page.getByRole('button',{name:'Execute & verify'}).click();
await page.locator('.live-failure').waitFor({timeout:45000});marks.failureAt=elapsed();
await page.locator('.live-failure').evaluate(el=>el.scrollIntoView({block:'start'}));await page.mouse.move(1480,850);
await page.screenshot({path:`demo/evidence/take-${take}-failure.png`});
console.log(JSON.stringify({take,phase:'real mismatch visible',seconds:marks.failureAt}));
const receipt=await finished(preview.plan.id);marks.executionSeconds=(Date.now()-executeStart)/1000;marks.finishedAt=elapsed();
if(receipt.verdict!=='SUCCESS'||receipt.mode!=='live'||receipt.results.filter(r=>r.recovered).length!==1)throw new Error('Recovery did not verify');
await page.getByRole('region',{name:'Recovery proof'}).waitFor();
await page.locator('.proof-strip').evaluate(el=>el.scrollIntoView({block:'start'}));await page.mouse.move(1480,850);
await page.screenshot({path:`demo/evidence/take-${take}-proof.png`});
await writeFile(`demo/evidence/take-${take}-receipt.json`,JSON.stringify(receipt,null,2));
console.log(JSON.stringify({take,phase:'live recovery verified',seconds:marks.finishedAt}));
if(marks.finishedAt>82)throw new Error('Take too slow for narration timeline.');
await at(88);await page.locator('.evidence').evaluate(el=>el.scrollIntoView({block:'start'}));await page.mouse.move(1480,850);
await page.screenshot({path:`demo/evidence/take-${take}-receipt.png`});
await at(103);await page.locator('.proof-strip').evaluate(el=>el.scrollIntoView({block:'start'}));await page.mouse.move(1480,850);
await at(config.durationSeconds);marks.contentSeconds=elapsed();marks.errors=errors;marks.receiptId=receipt.id;
const video=page.video();await context.close();const path=await video.path();await copyFile(path,`demo/raw/take-${take}.webm`);await browser.close();
await writeFile(`demo/evidence/take-${take}-timing.json`,JSON.stringify(marks,null,2));
console.log(JSON.stringify({...marks,phase:'recording saved',video:`demo/raw/take-${take}.webm`}));
if(errors.length)process.exitCode=1;
