import {useEffect,useState} from 'react';
import {recoveryProof,failureProof} from './proof.ts';
import type {Action,Plan,Receipt,Result} from '../src/domain.ts';
import type {Fault} from '../src/rehearsal.ts';
interface Status {clientReady:boolean;connected:boolean;seeded:boolean;busy:boolean;authError:string;modelConfigured:boolean;recent:Receipt[]}
interface Preview {plan:Plan;intent:{method:string;targetDate:string};mode:'live'|'rehearsal';fault:Fault}
const date=(s:string)=>new Date(s+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'UTC'});
const clock=(s:string)=>new Date(s).toLocaleTimeString('en-GB',{hour12:false});
async function api<T>(path:string,body?:unknown):Promise<T>{
 const res=await fetch('/api/'+path,body===undefined?undefined:{method:'POST',headers:{'Content-Type':'application/json','X-Mercury-Client':'1'},body:JSON.stringify(body)});
 const json=await res.json();if(!res.ok)throw new Error(json.error??'Request failed');return json;
}
function Badge({value}:{value:string}){return <span className={'badge '+value.toLowerCase()}>{value}</span>;}
function Graph({actions,results}:{actions:Action[];results:Result[]}){
 const positions=new Map<string,{x:number;y:number}>();
 const tasks=actions.filter(a=>a.app==='Sheets');const height=Math.max(300,90+tasks.length*95);
 for(const a of actions)positions.set(a.id,{x:a.app==='Calendar'?25:a.app==='Sheets'?285:545,y:a.app==='Sheets'?60+tasks.findIndex(t=>t.id===a.id)*95:height/2-20});
 return <div className="graph-scroll"><svg className="graph" viewBox={`0 0 780 ${height}`} role="img" aria-label="Dependency graph. Launch date propagates through task prerequisites to the launch brief.">
  <defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#aeb8c1"/></marker></defs>
  <text x="25" y="24" className="lane-label">GOOGLE CALENDAR</text><text x="285" y="24" className="lane-label">GOOGLE SHEETS</text><text x="545" y="24" className="lane-label">GOOGLE DOCS</text>
  {actions.flatMap(a=>a.dependsOn.map(id=>{const from=positions.get(id),to=positions.get(a.id);if(!from||!to)return null;const same=from.x===to.x;const d=same?`M ${from.x+105} ${from.y+67} L ${to.x+105} ${to.y}`:`M ${from.x+210} ${from.y+34} C ${from.x+235} ${from.y+34}, ${to.x-25} ${to.y+34}, ${to.x} ${to.y+34}`;return <path key={id+a.id} d={d} className="edge" markerEnd="url(#arrow)"/>;}))}
  {actions.map(a=>{const p=positions.get(a.id)!;const result=results.find(r=>r.id===a.id);return <g key={a.id} transform={`translate(${p.x},${p.y})`}><rect width="210" height="68" rx="7" className={'node '+(result?.verdict.toLowerCase()??'')}/><circle cx="15" cy="19" r="3" className={'dot '+(result?.verdict.toLowerCase()??'')}/><text x="25" y="23" className="node-title">{a.title.replace(/^Mercury · /,'').length>25?a.title.replace(/^Mercury · /,'').slice(0,24)+'…':a.title.replace(/^Mercury · /,'')}</text><text x="14" y="48" className="node-before">{date(a.value)}</text><text x="69" y="48" className="node-arrow">→</text><text x="90" y="48" className="node-after">{date(a.expected)}</text><text x="180" y="49" className="node-mark">{result?.recovered?'↺':result?.verdict==='SUCCESS'?'✓':result?.verdict==='FAILED'?'!':''}</text></g>;})}
 </svg></div>;
}
export function App(){
 const [status,setStatus]=useState<Status>();const [mode,setMode]=useState<'live'|'rehearsal'>('rehearsal');
 const [request,setRequest]=useState('Move our product launch from 2026-09-18 to 2026-09-22 and make sure nobody is left with stale information.');
 const [fault,setFault]=useState<Fault>('stale');const [preview,setPreview]=useState<Preview>();const [run,setRun]=useState<Receipt>();
 const [pending,setPending]=useState('');const [error,setError]=useState('');const [approved,setApproved]=useState(false);const [authUrl,setAuthUrl]=useState('');
 const refresh=()=>api<Status>('status').then(setStatus).catch(e=>setError(e.message));
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),5000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{
  if(!run||run.status!=='RUNNING')return;
  const timer=setInterval(()=>{void api<Receipt>('run/'+run.planId).then(setRun).catch(e=>setError('Execution status unavailable: '+e.message));},400);
  return()=>clearInterval(timer);
 },[run?.planId,run?.status]);
 const work=async(label:string,fn:()=>Promise<void>)=>{setPending(label);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Unknown error');}finally{setPending('');}};
 const reset=()=>{setPreview(undefined);setRun(undefined);setApproved(false);setError('');};
 const analyze=()=>work('Discovering dependencies',async()=>{reset();setPreview(await api<Preview>('plan',{request,mode,fault}));});
 const execute=()=>work('Starting execution',async()=>{if(!preview)return;await api('execute',{planId:preview.plan.id,approved});setRun(await api<Receipt>('run/'+preview.plan.id));});
 const actions=run?.actions??preview?.plan.actions??[];const results=run?.results??[];
 const verified=results.filter(r=>r.verdict==='SUCCESS').length;const recovered=results.filter(r=>r.recovered).length;
 const approvals=actions.filter(a=>a.risk==='APPROVAL');const blockers=run?.blockers??preview?.plan.blockers??[];
 const running=run?.status==='RUNNING';const disabled=Boolean(pending)||running;
 const proof=run?recoveryProof(run):null;
 const mismatch=run?failureProof(run):null;
 const changed=actions.filter(a=>a.value!==a.expected).length;
 const exportReceipt=()=>{if(!run)return;const url=URL.createObjectURL(new Blob([JSON.stringify(run,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`mercury-${run.mode}-${run.id}.json`;a.click();URL.revokeObjectURL(url);};
 return <div className={"shell "+(actions.length?"has-plan":"")}>
  <aside className="rail"><a className="brand" href="#" aria-label="Mercury home"><span className="logo">m</span><span>mercury<span className="brand-dot">.</span></span></a><span className="rail-caption">OPERATIONS</span><a className="nav active" href="#request"><span>↗</span> Recovery workspace</a><a className="nav" href="#evidence"><span>≡</span> Evidence receipt</a><div className="rail-bottom"><div className="pulse"/>Single-operator workspace<small>Observe. Repair. Prove.</small></div></aside>
  <main>
   <header className="topbar"><span>Workspace <span className="slash">/</span> Product launch</span><div className="mode-control"><span className={'mode-dot '+mode}/><select aria-label="Execution mode" value={mode} disabled={disabled} onChange={e=>{reset();setMode(e.target.value as typeof mode);setFault('stale');}}><option value="rehearsal">Rehearsal · local fixtures</option><option value="live">Live · Google APIs</option></select></div></header>
   <div className="content">
    <div className="heading"><div><div className="eyebrow">CROSS-APP RECOVERY</div><h1>{actions.length?"Launch recovery, with proof.":<>A change is only done<br/>when it is proven.</>}</h1><p>Trace the impact. Repair the dependencies. Verify what actually changed.</p></div><div className="workspace-mark">M<span>/</span>01<small>LAUNCH OPERATIONS</small></div></div>
    {mode==='live'&&(!status?.connected||!status?.seeded)&&<section className="setup"><strong>Connect your dedicated demo workspace</strong><p>{!status?.clientReady?'Save your Google Desktop OAuth client to secrets/google-client.json.':!status.connected?'Client found. Sign in with your Google test account.':'Authorization saved. Create a private launch event, task register, and brief.'}</p><button disabled={disabled||!status?.clientReady} onClick={()=>void work(status?.connected?'Creating and verifying workspace':'Preparing sign-in',async()=>{if(status?.connected){await api('seed',{});await refresh();}else{const r=await api<{url:string}>('auth',{});setAuthUrl(r.url);}})}>{status?.connected?'Create demo workspace':'Prepare Google sign-in'}</button>{authUrl&&<a className="auth-link" href={authUrl} target="_blank" rel="noreferrer">Continue to Google in your browser ↗</a>}<small>No existing documents are selected. No messages are sent.</small></section>}
    <section className="request" id="request"><label htmlFor="intent" className="eyebrow">01 / WHAT CHANGED?</label><textarea id="intent" value={request} disabled={disabled} onChange={e=>{setRequest(e.target.value);reset();}} rows={2}/><div className="request-footer"><span><span className="tiny-dot"/> Preserve dependencies <span className="middle-dot">·</span> Verify every postcondition</span><button className="primary" onClick={()=>void analyze()} disabled={disabled||(mode==='live'&&!status?.seeded)}>{pending==='Discovering dependencies'?'Discovering…':'Analyze impact'} <span>↗</span></button></div></section>
    <div className="toolbar"><div className="apps"><span className="app-icon calendar">31</span>Calendar<span className="connector">—</span><span className="app-icon sheets">▤</span>Sheets<span className="connector">—</span><span className="app-icon docs">≡</span>Docs</div><label className="fault-label">Controlled fault <select aria-label="Controlled fault" value={fault} disabled={disabled} onChange={e=>{reset();setFault(e.target.value as Fault);}}><option value="none">None · happy path</option><option value="stale">Acknowledged stale write</option>{mode==='rehearsal'&&<><option value="reject">Mutation rejected</option><option value="conflict">Concurrent edit</option><option value="unreadable">Readback unavailable</option><option value="approval">Approval required</option></>}</select></label></div>
    {(error||(mode==='live'&&status?.authError))&&<div role="alert" className="error"><strong>INCONCLUSIVE</strong> {error||status?.authError}</div>}
    {mismatch&&<section className="live-failure" role="alert"><div className="eyebrow">INDEPENDENT VERIFICATION / MISMATCH DETECTED</div><h2>Success withheld. The date is still wrong.</h2><p>{mismatch.title}: {mismatch.acknowledged?'API acknowledged':'Write attempted'} · observed <strong>{date(mismatch.observed)}</strong> · expected <strong>{date(mismatch.expected)}</strong></p><small>Checking whether one safe repair can restore the desired state. Dependent work waits.</small></section>}
    {proof&&<section className="proof-strip" aria-label="Recovery proof">
      <div className="proof-strip-heading"><div><div className="eyebrow">CONTROLLED FAULT / {proof.mode==='live'?'LIVE API EVIDENCE':'REHEARSAL EVIDENCE'}</div><h3>Accepted is not recovered.</h3></div><span>{proof.title} · {proof.app}</span></div>
      <div className="proof-steps"><div><span className="proof-step-label">01 / API RESPONSE</span><strong>{proof.acknowledged?'Acknowledged':'Write failed'}</strong><small>Requested date: {date(proof.expected)}</small></div><div className="mismatch"><span className="proof-step-label">02 / INDEPENDENT READ</span><strong>{date(proof.observed)} <b>≠</b> {date(proof.expected)}</strong><small>Mismatch detected. Completion withheld.</small></div><div className="repair"><span className="proof-step-label">03 / REPAIR + FINAL READ</span><strong>{date(proof.repaired)} <b>✓</b></strong><small>{proof.attempts} attempts total · verified {clock(proof.verifiedAt)}</small></div></div>
      <div className="proof-strip-footer"><span>{proof.mode==='live'?'Real API write, separate external reads.':'Local fixture run. This is not proof of live integration.'}</span>{proof.url&&<a href={proof.url} target="_blank" rel="noreferrer">Inspect external record ↗</a>}</div>
    </section>}
    <div className="workspace-grid"><section className="impact panel"><div className="panel-heading"><div><div className="eyebrow">02 / BLAST RADIUS</div><h2>{actions.length?`${actions.length} dependencies. One connected change.`:'See what this change touches.'}</h2></div><span className="subtle">{actions.length?`${new Set(actions.map(a=>a.app)).size} applications`:'Awaiting discovery'}</span></div>
      {actions.length?<><Graph actions={actions} results={results}/><div className="graph-footer"><span><i/> Discovered dependency</span><span>{new Set(actions.filter(a=>a.app==='Sheets').map(a=>a.owner)).size} task owners <span className="middle-dot">·</span> {changed} date changes</span></div></>:<div className="empty"><div className="empty-chain"><span>31</span><i/><span>▤</span><i/><span>≡</span></div><h3>The launch is connected to more than a date.</h3><p>Analyze the request to discover task prerequisites,<br/>owners, and the launch brief.</p></div>}
    </section><aside className="assurance panel"><div className="eyebrow">03 / EXECUTION CONTRACT</div><h2>{run?running?'Verifying external state':run.verdict==='SUCCESS'?'Recovery proven.':'Attention required.':'Safe to proceed?'}</h2><div className="proof-number">{verified}<span> / {actions.length||'—'}</span></div><p className="proof-caption">postconditions independently verified</p><div className="contract-row"><span>Automatic changes</span><strong>{actions.filter(a=>a.risk==='AUTO').length}</strong></div><div className="contract-row"><span>Require approval</span><strong>{approvals.length}</strong></div><div className="contract-row"><span>Recovered</span><strong>{recovered}</strong></div>
      {approvals.length>0&&!run&&<label className="approval"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/>Approve external-facing changes: {approvals.map(a=>a.title).join(', ')}. Calendar guests may receive updates.</label>}
      {blockers.length>0&&<ul className="blockers">{blockers.map((b,i)=><li key={i}>{b}</li>)}</ul>}
      {!run?<button className="primary execute" onClick={()=>void execute()} disabled={!preview||disabled||blockers.length>0||(approvals.length>0&&!approved)}>Execute & verify <span>→</span></button>:<div className="verdict" aria-live="polite"><Badge value={running?'VERIFYING':run.verdict}/><p>{running?'A receipt is being written after every observation.':run.verdict==='SUCCESS'?'Every scoped postcondition was observed in the desired state.':'Verified changes remain recorded. Unresolved work is not complete.'}</p></div>}
      <small className="scope-note">{mode==='rehearsal'?'REHEARSAL · No external applications are changed. Results prove fixture behavior only.':'LIVE · Changes target the dedicated Google sandbox. Verification is point-in-time.'}</small>
    </aside></div>
    {actions.length>0&&<section className="panel evidence" id="evidence"><div className="panel-heading"><div><div className="eyebrow">04 / EVIDENCE RECEIPT</div><h2>{run?'What is now proven.':'The plan, before anything changes.'}</h2></div>{run&&<button className="secondary" onClick={exportReceipt}>Export receipt ↓</button>}</div><div className="table-scroll"><table><thead><tr><th>Entity / owner</th><th>Before</th><th>Expected</th><th>Observed</th><th>Verdict</th></tr></thead><tbody>{actions.map(a=>{const r=results.find(x=>x.id===a.id);const observation=r?.observations.at(-1);return <tr key={a.id}><td>{a.url?<a href={a.url} target="_blank" rel="noreferrer">{a.title} ↗</a>:<strong>{a.title}</strong>}<small>{a.app} · {a.owner}</small></td><td>{date(a.value)}</td><td>{date(a.expected)}</td><td>{observation?.value?date(observation.value):'Not observed'}{observation&&<small>{clock(observation.at)}</small>}</td><td><Badge value={r?.verdict??a.risk}/>{r?.recovered&&<small className="recovered-label">↺ recovered</small>}</td></tr>;})}</tbody></table></div>
      <div className="details-list">{actions.map(a=>{const r=results.find(x=>x.id===a.id);return <details key={a.id}><summary>{a.title}<span>{r?.reason??a.reason}</span></summary><p>{a.reason}. Prerequisites: {a.dependsOn.join(', ')||'launch root'}. External ID: <code>{a.externalId}</code></p>{r&&<div className="trace">{r.attempts.map((x,i)=><div key={'a'+i}><time>{clock(x.at)}</time><strong>Write {i+1}</strong><span>{x.acknowledged?'API acknowledged':x.error??'Awaiting response'}</span></div>)}{r.observations.map((x,i)=><div key={'o'+i}><time>{clock(x.at)}</time><strong>{x.phase}</strong><span>{x.error??x.value}</span></div>)}</div>}</details>;})}</div>
      <footer className="receipt-footer"><span>{run?`${run.mode.toUpperCase()} / ${run.id.slice(0,8)} / ${run.status}`:preview?.intent.method}</span><span>Tool success ≠ task success.</span></footer>
    </section>}
    {status?.recent.length? <details className="history"><summary>Recent receipts ({status.recent.length})</summary>{status.recent.map(r=><button key={r.id} disabled={disabled} onClick={()=>{setRun(r);setMode(r.mode);setPreview(undefined);}}>{r.mode} · {clock(r.startedAt)} · {r.verdict}</button>)}</details>:null}
    <footer className="page-footer"><span>MERCURY / CROSS-APP RECOVERY</span><span>What changed. What broke. What recovered. What is proven.</span></footer>
   </div>
  </main>
 </div>;
}
